### PR TITLE
feature comment student

### PR DESCRIPTION
**Pull request by Poomffi**

### CODE REVIEW

**Comment by Poomffi** [comment]
review student

**Comment by naiithink** [comment]
Thanks for your contribution.

Could you please briefly explain this feature -- from both user and developer perspectives?
I need some more context to make a comprehensive decision on merging.

For example:
What are the UI changes?
What type of comment are they supposed to be?
What has been altered or added to the existing database schema on the base branch?

**Comment by Poomffi** [comment]
this a feature to teacher can review student.
example: inclass monday 4 pm have 3 childen that teacher can tack image and message to send the parent for the class;
childen 1 : to day we learn free style pose and Attach file image;
childen 2 : to day Hold your breath in water 60 second and Attach file image;
childen 3 : Is not coming don't have a review;

and parent can see the history my son have to learn something;

**Comment by naiithink** [comment]
Thanks for explaining.

I've reviewed your changes and have a couple of questions and a suggestion:
1. Why isn't there an image reference field in the 'student_attendances' table?
2. Did you forget to write/update the seeders?

I'd like to kindly suggest that the field 'student_attendances(review_comment)' should have been defined as nullable, rather than having its default value set to some arbitrary string -- "Lorem..."

@SaluteKevin @ingfosbreak Could you two please review the UI changes? I've done the database part.

**Comment by ingfosbreak** [comment]
After the consideration.

Here are the the few things that need to be fix.

1. หน้าที่ conflict กับ ตี๋
2. หน้าที่ภูมิ เขียน default เป็น lorem ipsun
3. database แก้เป็น nullable
4. controller function get my class แก้จาก $user => $user->id

sincerely,
INK

**Pull request closed without merging**
